versions:
   tomcat:  8.0.36
   
base_dirs:
   tomcat: /opt/tomcats
   software: /home/michael/git/ansible-presso/software

dirs:
   tomcat_tars:      "{{ base_dirs.tomcat }}/install_tars"
   catalina_home:    "{{ base_dirs.tomcat }}/apache-tomcat-{{ versions.tomcat }}"
   tomcat_instances:  "{{ base_dirs.tomcat }}/instances"

files:
   tomcat_install_tar: apache-tomcat-8.0.36.tar.gz

users:
   tomcat_home: { user: tc-user, uid: 4001, gid: 4001 }
   tomcat_app1: { user: tc-app1, uid: 4002, gid: 4002 } 
   tomcat_app2: { user: tc-app2, uid: 4003, gid: 4003 } 

tomcat_instances
   tc-app1:
      name: tc-app1

#CATALINA_HOME 
#CATALINA_BASE	
